# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.define "server" do |s|
      s.vm.network "private_network", ip: "192.168.56.101"
      s.vm.network :forwarded_port, guest: 3000, host: 3000
      s.vm.provision "shell", path: "server.sh"
  end
  config.vm.define "client" do |c|
      c.vm.network "private_network", ip: "192.168.56.102"
      c.vm.provision "shell", path: "client.sh"
  end
end
